name: Build and Deploy Frontend Docker Image

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama principal

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: cristindavid0124/blackjack-frontend:latest  # Imagen actualizada en Docker Hub

  deploy:
    runs-on: ubuntu-22.04
    needs: build-and-push

    steps:
    - name: Deploy to Azure App Service
      env:
        AZURE_WEBAPP_NAME: "BlackJackRoyaleApp"  # Nombre del App Service (frontend)
        AZURE_RESOURCE_GROUP: "BlackJackRoyaleApp_group"  # Nombre del grupo de recursos en Azure
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: |
        az login --service-principal \
          --username $AZURE_CLIENT_ID \
          --password $AZURE_CLIENT_SECRET \
          --tenant $AZURE_TENANT_ID
        az webapp config container set \
          --name $AZURE_WEBAPP_NAME \
          --resource-group $AZURE_RESOURCE_GROUP \
          --docker-custom-image-name cristindavid0124/blackjack-frontend:latest \
          --docker-registry-server-url https://index.docker.io/v1/
